"""Charge rules part A: violent person crimes."""
from __future__ import annotations

from typing import List, Tuple

_RULES_A: List[Tuple[str, List[str]]] = [
    (
        "homicide",
        [
            r"\bmurder\b", r"\bhomicide\b", r"\bmanslaughter\b",
            r"\bvoluntary\s+manslaughter\b", r"\binvoluntary\s+manslaughter\b",
            r"\bvehicular\s+homicide\b", r"\bcriminal\s+homicide\b",
            r"\bmurd", r"\bmud+er\b", r"\bmrd+er\b",
            r"\bvolun\s+mansl", r"\bdeath\s+by\s+vehicle",
        ],
    ),
    (
        "sex_crimes",
        [
            r"\brape\b", r"\bsexual\s+assault\b", r"\bsex\s+offense\b",
            r"\bsex\s+offenc", r"\bsexual\s+abuse\b", r"\bsexual\s+battery\b",
            r"\bindecent\s+(libert|expos|assault|act)",
            r"\bindecency\b", r"\bindency\b",
            r"\blewd\b", r"\blewdness\b", r"\bopen\s+lewd",
            r"\bchild\s+mol", r"\bmolest", r"\bsodomy\b",
            r"\binvoluntary\s+deviate\b", r"\bdeviate\s+sexual\s+intercourse\b",
            r"\bdeviatesexual\s+intercourse\b", r"\bidsi\b",
            r"\bsexual\s+intercourse\b", r"\bcarnal\s+knowledge\b",
            r"\bgross\s+sexual\s+imposition\b", r"\bsexual\s+imposition\b",
            r"\bcriminal\s+sexual\s+conduct\b", r"\bcsc\s*\d", r"\bcsc\b",
            r"\bsexual\s+contact\b", r"\babusive\s+sexual\s+contact\b",
            r"\bsexual\s+indecen", r"\bpublic\s+(?:sexual\s+)?indecen",
            r"\bcorruption\s+of\s+(a\s+)?minors?\b",
            r"\bunlawful\s+contact\s+with\s+(a\s+)?minor",
            r"\bvoyeur", r"\bpeeping\b", r"\bbestiality\b", r"\bimportun",
            r"\bcontinuous\s+sexual", r"\bsexual\s+performance\b",
            r"\bstatutory\s+sexual", r"\bsex(?:ual)?\s+seduction\b",
            r"\bsex\s+w/?\s*mnr", r"\bsex(?:ual)?\s+with\s+(a\s+)?min",
            r"\bpornograph", r"\bchild\s+porn", r"\bcsam\b",
            r"\bobscene\s+(?:matter|material)", r"\btransmitting\s+obscene",
            r"\btrans\s*/\s*dstrbtn\s+mat", r"\bmat(?:erial)?\s+dep(?:ict|i)\.?\s*child",
            r"\bprostitution\b", r"\bpatroniz\w*\s+prostitut",
            r"\bsex\s+traffick", r"\bhuman\s+traffick",
            r"\bsolicit\w*\s+.*(sex|prostitu|minor)", r"\bpandering\b",
            r"\bonline\s+solicit(?:ation)?\s+(?:of\s+)?(?:a\s+)?minor",
            r"\bsolicit(?:ation)?\s+(?:of\s+)?(?:a\s+)?(?:minor|child)\b",
            r"\binvasion\s+of\s+privacy.*(sex|intimate)",
            r"\bunlawful\s+sexual", r"\bsexual\s+conduct",
            r"\bforcible\s+fondl", r"\bfondling\b", r"\bfondl",
            r"\bsex\s+crime", r"\bsexually\s+violent",
            r"\bsex(?:ual)?\s+motivat",
            r"\bfailure\s+to\s+register.*(sex|offender)",
            r"\bsex\s+offender", r"\bregistry.*(sex|offender)",
            r"\benticing\s+a\s+(child|minor)", r"\bluring\s+a\s+minor",
            r"\bcoercion.*(?:sex|force).*sex", r"\bentice\w*.*illegal\s+sexual",
            r"\b21\.11\b", r"\b3123\b", r"\b288\b", r"\b261(?:\.5)?\b",
            r"\b18\s*usc\s*224[0-9]", r"\b18\s*usc\s*2422",
            r"\b13a-6-11[01]\b", r"\b13a-6-6[0-9]\b",
            r"\b5-14-1[0-9]{2}\b", r"\b200\.368\b", r"\b201\.23\b",
            # NC/IL jail abbreviations (match expanded forms: SEX→Sexual, AGG→Aggravated)
            r"\bpred\s+crim\s+sex", r"\bsex(?:ual)?\s+offender\s+regis",
            r"\bsex(?:ual)?\s+off.*fail", r"\baggr(?:avated)?\s+sex(?:ual)?\s+aslt",
            r"\bcrim\s+sex(?:ual)?\s+aslt", r"\bsex(?:ual)?\s+exploit",
            r"\bcrime\s+against\s+nature", r"\bsexually\s+dangerous",
            r"\bsexual\s+offense\s+\d", r"\bsex(?:ual)?\s+aslt\b",
            r"\bsol\s+sex\s+by\s+computer", r"\bsex(?:ual)?\s+offse\s+sub",
            r"\bviolent\s+off.*fail\s+regis", r"\bincest\b",
            r"\bmaterial\s+harmful\s+to\s+minors",
            r"\bfail.*register.*sex(?:ual)?\s+off",             r"\bsex(?:ual)?\s+off.*register",
            r"\bfail.*comply.*sex(?:ual)?\s+off",               r"\bsex(?:ual)?\s+off.*(?:rept|report|comply)",
            r"\bsexoff", r"\bsex(?:ual)?\s+offender.*(?:false|child|premises|school)",
            r"\bchild\s+sex(?:ual)?\s+offender", r"\bforcible\s+sex",
            r"\bindec(?:ent)?\s+(?:w|sol).*child", r"\bgrooming\b",
            r"\btravel.*meet.*minor", r"\bcyberstalk",
            r"\bindec(?:ent)?\s+(?:sol|pred)",
            r"\bcrim(?:inal)?\s+sex(?:ual)?\s+ab", r"\bstat(?:utory)?\s+sex",
            r"\bsex(?:ual)?\s+off(?:ense|n)?\s*w/?\s*child",
            r"\bnonconsensual.*(?:sex|image)", r"\bdisclosure.*private\s+image",
            r"\bdissem.*harm.*mater.*minor",
        ],
    ),
    (
        "robbery",
        [
            r"\brobbery\b", r"\barmed\s+robbery\b", r"\bcarjack",
            r"\bstrong.?arm\b", r"\bvehicular\s+hijack",
        ],
    ),
    (
        "burglary_be",
        [
            r"\bburglar", r"\bb\s*&\s*e\b", r"\bb\s+and\s+e\b",
            r"\bbreaking\s+and\s+enter", r"\bbreak\s+and\s+enter",
            r"\bbreaking\s+and\s+or\s+enter", r"\bbreaking\s+or\s+enter",
            r"\bbreak\s*/\s*enter", r"\bbreak/?enter",
            r"\bunlawful\s+entry\b", r"\bhome\s+invasion\b",
            r"\benter(ing)?\s+(a\s+)?(dwell|build|struct)",
            r"\bburglary\s+tools\b",
            r"\bburg\s+habit", r"\bcrim\s+tres.*res.*pers",
            r"\bburg.*habit", r"\bburg\s+bldg", r"\bburg\s+hab\b",
        ],
    ),
    (
        "weapons",
        [
            r"\bfirearm", r"\bhandgun\b", r"\brifle\b", r"\bshotgun\b",
            r"\bweapon", r"\bgun\b", r"\bammunition\b", r"\bconcealed\s+carry",
            r"\bunlawful\s+poss.*weapon", r"\bposs.*firearm",
            r"\bbrandish", r"\bdeadly\s+weapon", r"\bknife\b",
            r"\bexplosive", r"\bdestructive\s+device",
            r"\buuw\b", r"\bfoid\b", r"\bwpn\b", r"\bfelon.*poss.*wpn",
            r"\bfelon.*(?:firearm|f\s*/?\s*arm)",
        ],
    ),
    (
        "domestic",
        [
            r"\bdomestic\b", r"\bfamily\s+violence\b", r"\bfamily\s+abuse\b",
            r"\bintimate\s+partner", r"\bprotection\s+order",
            r"\brestraining\s+order", r"\bviolat.*(protect|restrain)",
            r"\bdomestic\s+assault", r"\bdomestic\s+batter",
            r"\basslt\s+cbi\s+fv\b", r"\bcbi\s+fv\b",
            r"\babuse\s+spousal\b", r"\bspousal\s+abuse\b",
            r"\bbat\s*:\s*spouse", r"\bbattery\s+spouse",
            r"\bchild\s+abuse\b", r"\bchild\s+endanger", r"\bneglect\s+of\s+child",
            r"\belder\s+abuse\b",
            r"\b273\.5\b", r"\bcorp(?:oral)?\s+inj(?:ury)?.{0,20}\b(spouse|cohab)",
            r"\binf\s+corp\s+inj",
            r"\bvio\s+order.*prior\s+vio", r"\bviolat.*order.*prior\s+viol",
            r"\baslt\s+fam", r"\bexploit\s+elder",
        ],
    ),
    (
        "violent",
        [
            r"\bassault\b", r"\bbatter(?:y|ing)\b", r"\baggravated\s+assault",
            r"\bfelonious\s+assault", r"\bstalking\b", r"\bharass",
            r"\bkidnap", r"\bfalse\s+imprison", r"\bunlawful\s+restraint",
            r"\bunl\s+restraint", r"\basslt\b", r"\bstrangul",
            r"\bterroristic\s+threat", r"\bthreat\s+to\s+(kill|injure)",
            r"\bmens?\s+rea.*assault", r"\bmayhem\b", r"\briot\b",
            r"\bresist(ing)?\s+(arrest|officer)", r"\baffray\b",
            r"\bintimidation\b", r"\bmalicious\s+wound",
            r"\btouch\s*(?:or|/|&)\s*strike\b",
            r"\bstrike\s*(?:or|/|&)\s*touch\b",
            # NC/IL jail abbreviations (match expanded forms too)
            r"\bawdw", r"\baggr(?:avated)?\s+aslt", r"\baslt\s+peace\s+off",
            r"\bcommunicating\s+threats", r"\bmenacing\b",
            r"\bfelonious\s+restraint", r"\bmalicious.*wound",
            r"\bserious\s+inj.*vehicle",             r"\bhit\s*(?:/|\s+)\s*run",
            r"\bmissile\s+into\s+dwelling", r"\bthreaten\s+public\s+official",
            r"\bmob\s+action", r"\bcruelty\s+to\s+animal",
            r"\bmalicious.*inj.*prop", r"\bwanton\s+inj",
            r"\bwill.*want.*inj.*prop",
            r"\baslt\s+public\s+servant", r"\breckless\s+conduct",
            r"\bhrsm?t.*threaten", r"\bdisarm.*off",
            r"\bcommunicate.*detain.*witness",
            r"\baslt.*(?:law\s+off|pub\s+serv)", r"\barm\s+terror",
            r"\binjury\s+to\s+child", r"\bintimidate\s+witness",
        ],
    ),
]
