"""Charge rules part B: drugs, traffic, fraud, theft, order."""
from __future__ import annotations

from typing import List, Tuple

_RULES_B: List[Tuple[str, List[str]]] = [
    (
        "drugs",
        [
            r"\bcontroll?ed\s+substance", r"\bnarcotic", r"\bdrug\b",
            r"\bcocaine\b", r"\bheroin\b", r"\bfentanyl\b", r"\bmeth(amphetamine)?\b",
            r"\bmarijuana\b", r"\bcannabis\b", r"\bposs(ession)?\s+of\s+.*(drug|marij|cocaine|heroin|meth|fentanyl|opium|opioid)",
            r"\bpossess.*cds\b", r"\bcds\b", r"\bdelivery\s+of\b",
            r"\btraffick.*drug", r"\bdrug\s+traffick", r"\bintent\s+to\s+(distrib|deliver|sell)",
            r"\bparaphernalia\b", r"\bpwid\b",
            r"\bdrug\s+equip(?:ment)?", r"\bequip(?:ment)?\s*[-–—/]?\s*possess",
            r"\bman\.?\s*delv", r"\bman(?:ufacture)?\s*/?\s*del(?:iv(?:ery)?)?",
            r"\bposs\.?\s+cont\.?\s+sub", r"\bcont\.?\s+subs?\b",
            r"\bposs\s+cs\b", r"\bposs\s+marij",
            # NC schedule system + IL/FL jail shorthand (match expanded forms)
            r"\bsched(?:ule)?\s+[ivx]+\b", r"\bposs(?:ession)?\s+amt\s+con(?:t(?:rol(?:led)?)?)?\s+sub(?:stance)?",
            r"\bmanu(?:facture)?\s*(?:/|\s+)\s*del", r"\bdel(?:ivery)?\s*(?:/|\s+)\s*sell",
            r"\bposs(?:ess(?:ion)?)?\s+wits?\b",
            r"\bmaint.*place.*cont(?:roll?ed)?", r"\bcont(?:roll?ed)?\s+sub(?:s|stance)?\s+act",
            r"\bsell\s+(cont(?:roll?ed)?|sched)", r"\bmanuf.*sched",
            r"\blook-?alike\s+sub", r"\btraffick.*sched",
            r"\bposs(?:ess(?:ion)?)?\s+sched(?:ule)?", r"\bmanufacture\s+sched",
            r"\banhydrous\s+ammonia", r"\becstacy\b", r"\blsd\b",
            r"\bmorphine\b", r"\bphencyclidine\b", r"\bpsylocibin",
            r"\bposs(?:ess(?:ion)?)?\s+cont(?:rol(?:led)?)?\s+sub(?:s|stance)?",
            r"\bcontl\s+sub", r"\bs\s+d\s+contl",
            r"\bposs(?:ess(?:ion)?)?\s+precursor",
            r"\btraffick.*cont(?:roll?ed)?", r"\becs?tasy",
            r"\bmanufacture\s+cont(?:rol)?", r"\bsniffing\s+glue",
            r"\bposs(?:ess)?.*pills?\s+ecs?tasy",
        ],
    ),
    (
        "dui_traffic",
        [
            r"\bdui\b", r"\bdwi\b", r"\bowi\b", r"\bovi\b",
            r"\bdriving\s+under\s+the\s+influence", r"\bdriving\s+while\s+intoxic",
            r"\bimpaired\s+driving", r"\bbac\b", r"\bblood\s+alcohol",
            r"\breckless\s+driving", r"\bspeeding\b", r"\bhit\s+and\s+run",
            r"\bleave\s+the\s+scene", r"\bno\s+license\b", r"\bsuspended\s+license",
            r"\bno\s+valid\s+(?:driver'?s?\s+)?license",
            r"\bno\s+driver'?s?\s+license",
            r"\bdriving\s+without\s+(?:a\s+)?(?:valid\s+)?(?:driver'?s?\s+)?license",
            r"\bno\s+operator", r"\brevoked\s+license",
            r"\btraffic\b", r"\bmv\s+offense", r"\bvehicle\s+code",
            r"\buninsured\s+(motor|vehicle)", r"\belude|eluding\b",
            # NC/IL/FL jail shorthand (match expanded forms: W/ → W, slashes removed)
            r"\bdriv.*(?:license\s+)?revok", r"\bdriving\s+w\s+(?:/\s*)?(suspend|revoke)",
            r"\bdriv.*license\s+perm\s+rvk", r"\boperat.*vehicle.*w\s*(?:/|\s)?\s*o\s+license",
            r"\bmisc.*motor\s+vehicle", r"\boper.*m\.?v\.?without.*fin",
            r"\bdriving\s+w\s+suspend", r"\bdriving\s+w\s+revoke",
            r"\bdriv\s+license\s+revok", r"\bfailure\s+report\s+accident",
            r"\bviolate\s+vehicle\s+registration",
            r"\baggr(?:avated)?\s+fleeing", r"\bevading\s+arrest",
            r"\bdriving\s+revoked", r"\bfailure\s+to\s+stop\s+for\s+accident",
            r"\bfail.*heed.*light.*siren", r"\bspeed.*eld.*arst",
            r"\bdriving\s+<\s*21\s+consume",
            r"\bevad.*arr(?:est)?", r"\bfail.*report.*accident",
        ],
    ),
    (
        "fraud_financial",
        [
            r"\bfraud\b", r"\bforgery\b", r"\bidentity\s+theft", r"\bid\s+theft",
            r"\bembezzl", r"\bcounterfeit", r"\bcredit\s+card", r"\bbad\s+check",
            r"\buttering\b", r"\bwelfare\s+fraud", r"\binsurance\s+fraud",
            r"\bmoney\s+launder", r"\bextortion\b", r"\bbribery\b",
            r"\btheft\s+by\s+deception", r"\bfalse\s+pretense",
            # NC/IL jail shorthand (match expanded forms)
            r"\bworthless\s+check", r"\bobt.*prop.*false",
            r"\bcheat.*property", r"\bhot\s+check", r"\bfalse\s+pretens",
            r"\bfiduc.*prop", r"\bmisapp.*fid", r"\bmoney\s+laund",
            r"\bobtain\s+prop.*false", r"\bnegotiat.*worthless",
            r"\bdefraud", r"\bfalse\s+pr.*chts",
            r"\bunlawful\s+poss.*credit", r"\bincome\s+tax",
            r"\buse\s+forged\s+credit",             r"\bcontinuing\s+finance",
            r"\bbad\s+chk", r"\bfraudulent\s+id",
            r"\bid\s+thft", r"\binterfer.*meter", r"\bunauthorized.*title",
        ],
    ),
    (
        "theft_property",
        [
            r"\btheft\b", r"\blarceny\b", r"\bshoplift", r"\bstolen\s+propert",
            r"\breceiv(ing|ed)\s+stolen", r"\bmotor\s+vehicle\s+theft",
            r"\bauto\s+theft", r"\bgrand\s+theft", r"\bpetit\s+theft",
            r"\bpetty\s+theft", r"\bvandal", r"\bcriminal\s+mischief",
            r"\bproperty\s+damage", r"\barson\b", r"\btrespass",
            r"\bunlawful\s+taking",
            # NC/IL jail shorthand (match expanded forms)
            r"\bstolen\s+veh", r"\bpossess.*stolen\s+goods",
            r"\bunauth.*use.*motor.*convey", r"\bconversion\s+by\s+bailee",
            r"\bkeeping\s+hired\s+property", r"\bfail.*return.*rented",
            r"\btamper.*motor\s+vehicle", r"\bmeddling.*motor\s+vehicle",
            r"\bdamage\s+to\s+property", r"\bcrim\.?\s* dmg",
            r"\bburning.*property", r"\borg\s+retail\s+th",
            r"\bsecret\s+prop\s+hinder", r"\bobtain.*property.*worthless",
            r"\bunlawful\s+poss.*(?:driver|veh).*stolen",
            r"\bcrim(?:inal)?\s+damage?\s+prop",
            r"\bcriminal\s+damage", r"\bburning.*building",
            r"\bstolen\s+title", r"\binjure.*house",
        ],
    ),
    (
        "public_order",
        [
            r"\bdisorderly\b", r"\bpublic\s+intoxic", r"\bdrunk\s+in\s+public",
            r"\bloitering\b", r"\bcurfew\b", r"\bnoise\b",
            r"\bobstruct(ing)?\s+(justice|officer|police)",
            r"\bfalse\s+report", r"\bperjury\b", r"\bcontempt\b",
            r"\bfugitive\b", r"\bescape\b", r"\bbail\s+jump",
            r"\bwarrant\b", r"\bprobation\s+viol", r"\bparole\s+viol",
            r"\bopen\s+container", r"\blitter",
            # NC/IL jail shorthand (match expanded forms)
            r"\bhabitual\s+felon", r"\barmed\s+habitual",
            r"\bresist.*obstruc.*officer", r"\bobstruc.*just.*destroy",
            r"\bconspiracy\b", r"\baccessory.*after.*fact",
            r"\bmalicious\s+conduct.*prison", r"\bcontraband.*penal",
            r"\bfelon.*fail.*return.*furlough", r"\binterfering.*emergency",
            r"\bfalse\s+rpt.*police", r"\bfictitious\s+info.*law",
            r"\bprofane\s+language", r"\bprof.*harrss.*threat.*phone",
            r"\bmisuse.*911", r"\bnon-?support", r"\bcontri.*delinq.*minor",
            r"\bschool\s+attend.*law", r"\bemploy\s+sec\s+viol",
            r"\bviolation\s+social\s+services", r"\bout\s+of\s+state\b",
            r"\bobstruct.*gov", r"\bresist.*officer.*injury",
            r"\bviolat.*court\s+order", r"\bviolation\s+of\s+court\s+order",
            r"\bmunicipal\s+ordinance", r"\border\s+of\s+commitment",
            r"\border\s+of\s+arrest", r"\bmittimus", r"\border\s+to\s+incarcerate",
            r"\bconsume.*alch.*<\s*21", r"\bmalt\s+bev.*<\s*21",
            r"\bminor.*poss.*alcohol", r"\bunderage.*consum",
            r"\bunlawful\s+vehicular\s+invasion",
            r"\bfailure\s+to\s+appear", r"\bfta\b",
            r"\bopen\s+cont.*alcohol", r"\bgame\s+law",
            r"\binterfere.*elect.*monitor",             r"\bfoil.*screen\s+test",
            r"\borg\s+crim", r"\bretaliation", r"\bfalse\s+alarm",
            r"\bimmigration\b", r"\bliquor", r"\blocal\s+ordinance",
            r"\bregulation\s+liquor", r"\brefuse.*false.*infor.*officer",
        ],
    ),
]

